import common from "./common/common"
import detail from "./detail/detail"
import receiveGoodsAddress from "./receiveGoodsAddress/receiveGoodsAddress"

const service = {
  namespaced: true,
  modules:{
    common:common,
    detail:detail,
    receiveGoodsAddress:receiveGoodsAddress,
  },
  state: {
    // 家政帮
    housekeep:{
      serviceType:{         //服务类型
        input1:{
          value:'',
          name:''
        },
        input2:'',
        input3:'',
      },
      housekeepPhoto:{
        input1:'',
        input2:{
          items:[],
          files:[]
        }
      },
      housekeepAddress:{
        input1:{
          value:['410000','410100','410103'],
          name:['河南省','郑州市','二七区']
        },
        input2:''      //高德地址
      },
      housekeepTime:{
        input1:{value:'1',name:'立即购买'},
        input2:0
      },
      quicken:{
        input1:0,
        labelText:['无加速','5元','10元','自定义'],
        input2:null,
      }
    },
    // 维修帮
    repair:{
      serviceType:{         //服务类型
        input1:{
          value:'',
          name:''
        },
        input2:'',
        input3:'',
        input4:'',
      },
      housekeepPhoto:{
        input1:'',
        input2:{
          items:[],
          files:[]
        }
      },
      housekeepAddress:{
        input1:{
          value:['410000','410100','410103'],
          name:['河南省','郑州市','二七区']
        },
        input2:''         //高德地址
      },
      housekeepTime:{
        input1:{value:'1',name:'立即购买'},
        input2:''
      },
      quicken:{
        input1:0,
        labelText:['无加速','5元','10元','自定义'],
        input2:null,
      }
    },
    // 司机帮
    driver:{
      serviceType:{         //服务类型
        input1:{
          value:'',
          name:''
        },
        input2:'',
        input3:'',
      },
      housekeepPhoto:{
        input1:'',
        input2:{
          items:[],
          files:[]
        }
      },
      housekeepAddress:{
        input1:{value:['410000','410100','410103'],name:['河南省','郑州市','二七区']},
        input2:'',
        input3:{value:['410000','410100','410103'],name:['河南省','郑州市','二七区']},
        input4:'',
      },
      housekeepTime:{
        input1:{value:'',name:''},
        input2:''
      },
      quicken:{
        input1:0,
        labelText:['无加速','5元','10元','自定义'],
        input2:null,
      }
    },
    // 公益帮
    commonweal:{
      serviceType:{         //服务类型
        input1:'',
        input2:''
      },
      commonwealNameLine:{
        input1:'',
        input2:''
      },
      housekeepPhoto:{
        input1:'',
        input2:{
          items:[],
          files:[]
        }
      },
      remarks:{
        label:'截止时间',
        input1:'',
        input2:'请选择截至时间'
      },
    },
    // 找帮手
    helper:{
      serviceType:{         //服务类型
        input1:'',
        input2:'',
        input3:'',
      },
      housekeepPhoto:{
        input1:'',
        input2:{
          items:[],
          files:[]
        }
      },
      housekeepAddress:{
        input1:{
          value:['410000','410100','410103'],
          name:['河南省','郑州市','二七区']
        },
        input2:''   //高德地址
      },
      remarks:{
        label:'预约时间',
        input1:'',
        input2:{value:'',name:''}
      },
      priceLine:{
        input1:5,
        input2:''
      },
      integralLine:{
        input1:null
      },
    },
    // 跑腿
    runTo:{
      helpMe:{
        id:'',
        adcode:'',
        input1:'',
        input2:'',
        input3:'',
      },
      goumaiGoods:{
        input1:'',
        input2:{value:'1',name:'1'}
      },
      goumaiGoodsAddress:{
        adcode:'',
        input1:true,
        input2:'',
        input3:'',
      },
      remarks:{
        label:'备  注',
        input1:'',
        input2:''
      },
      quicken:{
        input1:0,
        labelText:['无加速','5元','10元','自定义'],
        input2:null,
      }
    },
    runTo1:{
      helpMe:{
        id:'',
        adcode:'',
        input1:'',
        input2:'',
        input3:'',
        id1:'',
        adcode1:'',
        input4:'',
        input5:'',
        input6:'',
      },
      goumaiGoods:{
        input1:'',
        input2:{value:'1',name:'1'}
      },
      housekeepTime:{
        input1:null,
        input2:'',
      },
      remarks:{
        label:'备  注',
        input1:'',
        input2:''
      },
      quicken:{
        input1:0,
        labelText:['无加速','5元','10元','自定义'],
        input2:null,
      }
    },

    runToState:'',
    driverAddressState:'',    //00:第一个详细地址   01:第二个详细地址
    mapAddr:'',
    mapAddressArr:[],
    mapAdcode:'410103',
    mapStreet:'',
    addressState:'',    //  00:指定买   01:runTo_1      11:runTo1_1    12:runTo1_2

  },
  getters:{
    mapAdcodeArr(state){
      let arr = [];
      let a = state.mapAdcode;
      let b1 = a.substring(0,2)
      let b2 = a.substring(2,4)
      let b3 = a.substring(4,6)
      arr.push(b1+'0000');
      arr.push(b1+b2+'00');
      arr.push(b1+b2+b3);
      return arr;
    },
  },
  mutations:{
    initHousekeep(state){
      state.housekeep={
        serviceType:{         //服务类型
          input1:{
            value:'',
            name:''
          },
          input2:'',
          input3:'',
        },
        housekeepPhoto:{
          input1:'',
          input2:{
            items:[],
            files:[]
          }
        },
        housekeepAddress:{
          input1:{
            value:['410000','410100','410103'],
            name:['河南省','郑州市','二七区']
          },
          input2:''      //高德地址
        },
        housekeepTime:{
          input1:{value:'1',name:'立即购买'},
          input2:0
        },
        quicken:{
          input1:0,
          labelText:['无加速','5元','10元','自定义'],
          input2:0,
        }
      }
    },
    initRepair(state){
      state.repair={
        serviceType:{         //服务类型
          input1:{
            value:'',
            name:''
          },
          input2:'',
          input3:'',
          input4:'',
        },
        housekeepPhoto:{
          input1:'',
          input2:{
            items:[],
            files:[]
          }
        },
        housekeepAddress:{
          input1:{
            value:['410000','410100','410103'],
            name:['河南省','郑州市','二七区']
          },
          input2:''         //高德地址
        },
        housekeepTime:{
          input1:{value:'1',name:'立即购买'},
          input2:''
        },
        quicken:{
          input1:0,
          labelText:['无加速','5元','10元','自定义'],
          input2:0,
        }
      }
    },
    initDriver(state){
      state.driver={
        serviceType:{         //服务类型
          input1:{
            value:'',
            name:''
          },
          input2:'',
          input3:'',
        },
        housekeepPhoto:{
          input1:'',
          input2:{
            items:[],
            files:[]
          }
        },
        housekeepAddress:{
          input1:{value:['410000','410100','410103'],name:['河南省','郑州市','二七区']},
          input2:'',
          input3:{value:['410000','410100','410103'],name:['河南省','郑州市','二七区']},
          input4:'',
        },
        housekeepTime:{
          input1:{value:'',name:''},
          input2:''
        },
        quicken:{
          input1:0,
          labelText:['无加速','5元','10元','自定义'],
          input2:0,
        }
      }
    },
    initCommonweal(state){
      state.commonweal={
        serviceType:{         //服务类型
          input1:'',
          input2:''
        },
        commonwealNameLine:{
          input1:'',
          input2:''
        },
        housekeepPhoto:{
          input1:'',
          input2:{
            items:[],
            files:[]
          }
        },
        remarks:{
          label:'截止时间',
          input1:'',
          input2:'请选择截至时间'
        },
      }
    },
    initHelper(state){
      state.helper={
        serviceType:{         //服务类型
          input1:'',
          input2:'',
          input3:'',
        },
        housekeepPhoto:{
          input1:'',
          input2:{
            items:[],
            files:[]
          }
        },
        housekeepAddress:{
          input1:{
            value:['410000','410100','410103'],
            name:['河南省','郑州市','二七区']
          },
          input2:''   //高德地址
        },
        remarks:{
          label:'预约时间',
          input1:'',
          input2:{value:'',name:''}
        },
        priceLine:{
          input1:5,
          input2:''
        },
        integralLine:{
          input1:0
        },
      }
    },
    initRunTo(state){
      state.runTo={
        helpMe:{
          id:'',
          adcode:'',
          input1:'',
          input2:'',
          input3:'',
        },
        goumaiGoods:{
          input1:'',
          input2:{value:'1',name:'1'}
        },
        goumaiGoodsAddress:{
          adcode:'',
          input1:true,
          input2:'',
          input3:'',
        },
        remarks:{
          input1:'备  注',
          input2:''
        },
        quicken:{
          input1:0,
          labelText:['无加速','5元','10元','自定义'],
          input2:0,
        }
      }
    },
    initRunTo1(state){
      state.runTo1={
        helpMe:{
          id:'',
          adcode:'',
          input1:'',
          input2:'',
          input3:'',
          id1:'',
          adcode1:'',
          input4:'',
          input5:'',
          input6:'',
        },
        goumaiGoods:{
          input1:'',
          input2:{value:'1',name:'1'}
        },
        housekeepTime:{
          input1:0,
          input2:'',
        },
        remarks:{
          input1:'备  注',
          input2:''
        },
        quicken:{
          input1:0,
          labelText:['无加速','5元','10元','自定义'],
          input2:0,
        }
      }
    }
  },
  actions:{

  }
}

export default service;
